#!/usr/bin/env bash
# Script to install and setup HAProxy load balancer for two web servers

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install haproxy

config="\nlisten load-balancer
bind *:80
mode http
balance roundrobin
option httpclose
option forwardfor
server 106387-web-01 100.25.41.68:80 check
server 106387-web-02 34.207.121.230:80 check"

echo -e "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
