#!/usr/bin/env bash
# Script to install and setup HAProxy load balancer for two web servers

apt install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.4 -y
apt-get -y update
apt-get -y install haproxy=2.4.\*


config="\nlisten load-balancer
	bind *:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 106387-web-01 107.21.42.87:80 check
	server 106387-web-02 34.207.121.230:80 check"

echo -e "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
