#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`.
# Only displays the username, user id, and user home directory path.

while IFS= read -r line
do
    echo "$line" | cut -f 1,3,6 -d ':'
done < "/etc/passwd"
